### PR TITLE
Create bower.json

### PR DESCRIPTION
**Pull request by robertmain**
Create bower file to allow people using gulp/grunt etc. to integrate it into their workflow

### CODE REVIEW

**Comment by xbgmsharp** [comment]
:+1:

**Comment by WillemLabu** [comment]
:+1:

**Comment by 47ronin** [comment]
:+1::+1:

**Comment by pgrodrigues** [comment]
:+1:

**Comment by Misiu** [comment]
:+1:

**Comment by robertmain** [comment]
Accidentally deleted fork, but I re-created it for everyone's convenience. The new PR can be found at https://github.com/formvalidation/formvalidation/pull/1470. Thanks

**Pull request closed without merging**
