### PR TITLE
Added Polish zip code validator

### PR DESCRIPTION
**Pull request by tjagusz**
Hi, my first pull request to support Polish stuff.
Here is test case for regex: http://regexr.com/3a7oc
and reference: http://en.wikipedia.org/wiki/List_of_postal_codes_in_Poland

### CODE REVIEW

**Comment by tjagusz** [comment]
I've added also missing Polish translation and Polish ID validator.
We can get age from Polish ID number (PESEL) so I'm wondering how should I add age validator to it?
Use case:
-use must enter his ID and then validator check his age and shows that hit too young/old to submit form.
Should I create separate validator for that or can i somehow "connect it" with ID validator?

**Comment by nghuuphuoc** [comment]
The PR is awesome!
Can you add some test cases for Polish [id](https://github.com/formvalidation/formvalidation/blob/master/test/spec/validator/id.js) and [zipCode](https://github.com/formvalidation/formvalidation/blob/master/test/spec/validator/zipCode.js) validators?

**Comment by tjagusz** [comment]
I've added some tests. I hope they are valid.
There is one more thing to consider: In Poland we also have Identity cards (http://en.wikipedia.org/wiki/Polish_identity_card)
So there are two things in Poland: PESEL (http://en.wikipedia.org/wiki/National_identification_number#Poland, http://en.wikipedia.org/wiki/PESEL) and Identity Card number.
I'm not sure if there should be PESEL or Identity Card inside id validator.
I can add both, but how should I name them?

**Comment by nghuuphuoc** [comment]
Since PESEL is mentioned in http://en.wikipedia.org/wiki/National_identification_number#Poland as it covers other ID numbers used in the ID validator, I think it's ok to keep PESEL in current id validator.

Thank for your PR again. I will merge it now :+1:

**Comment by tjagusz** [comment]
And what about Identity Card? I also would like add that validator, but where?
I also have question about connected validators.
From PESEL I can get birth date and I would like to validate age after user inputs PESEL.
I would like to specify min and max valid age.
How can I do that?
My only idea for now is to create separate PESEL validator and in there have all age verification logic.
Maybe You could advice me better solution? :smiley:

**Comment by nghuuphuoc** [comment]
1) You can make another PR.
Some countries have many ID formats, such as [Spain](https://github.com/formvalidation/formvalidation/blob/master/src/js/validator/id.js#L958).
We can do the same for Poland.

2) If PESL contains the date of birth, we must validate it.
See [example](https://github.com/formvalidation/formvalidation/blob/master/src/js/validator/id.js#L958)

**Comment by tjagusz** [comment]
Polish identity card is something different that PESEL, it's not just format.
PESEL is given when a person is born and Identity Card is a document which person gets when turns 18.

PESEL is just a number assigned to every citizen (i know this might be weird), Polish identity card is  identification document or in other words proof of identity.

What do You say if I change id validator to verify Polish Identity Card, which I think should be there and I'll create second (separate) validator for PESEL with age validation.
I imagine it as so: You set validator type to PESEL and specify minimum age (and/or maximum) like so:

    validators: {
        pesel: {
            message: 'Not valid PESEL',
            minAge: 18,
            minAgeMessage: 'Too young',
            maxAge: 70,
            maxAgeMessage: 'Too old.'
        }
    }

Something like above.
What do You think?

**Comment by nghuuphuoc** [comment]
I'm so confused. So, at the end, the Polish identification number, as mentioned in http://en.wikipedia.org/wiki/National_identification_number#Poland should be PESEL or should be changed to Polish Identity Card?

**Pull request merged**
